{
 "title": "One Tap Soccer",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Goals Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_goal_total) / sum(com_redhat_onetapsoccer_shoot_total)"
    }
   ]
  },
  {
   "title": "Goals",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_goal_total)"
    }
   ]
  },
  {
   "title": "Games",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_game_start_total)"
    }
   ]
  },
  {
   "title": "Ground Collision",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_ground_collision_total)"
    }
   ]
  },
  {
   "title": "Pole Collision",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_pole_collision_total)"
    }
   ]
  },
  {
   "title": "Top Users Ranking",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Score" }
   ],
   "targets": [
    {
     "expr": "max by (userName) (com_redhat_onetapsoccer_score )",
     "legendFormat": "{{userName}}"
    }
   ]
  },
  {
   "title": "Shoots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_shoot_total)"
    }
   ]
  },
  {
   "title": "Game Over",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_game_over_total)"
    }
   ]
  },
  {
   "title": "Head Collision",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_head_collision_total)"
    }
   ]
  },
  {
   "title": "Collisions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_pole_collision_total) + sum(com_redhat_onetapsoccer_head_collision_total) + sum(com_redhat_onetapsoccer_ground_collision_total)"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (kind) (com_redhat_onetapsoccer_total))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_redhat_onetapsoccer_total)"
    }
   ]
  },
  {
   "title": "Unique Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (user) (com_redhat_onetapsoccer_game_start_total))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Rate last 60s. All POD, not only our container",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"kafka-cluster\", pod=~\"one-tap-soccer-event-consumer-.*\", container != \"POD\", container != \"\"}[1m])) "
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "All POD, not only our container",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 12 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"kafka-cluster\", pod=~\"one-tap-soccer-event-consumer-.*\", container != \"\"}) * 0.000001"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "description": "Pods Event consumers\nAfter update the ksvc, the number should be bigger than expected because it creates and terminates the pods",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"kafka-cluster\", pod=~\"one-tap-soccer-event-consumer-.*\"})"
    }
   ]
  },
  {
   "title": "Goals per Shirt",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (player) (com_redhat_onetapsoccer_total{kind=\"goal\"}))",
     "legendFormat": "{{player}}"
    }
   ]
  }
 ]
}