- name: Provision AMQ Streams
  include_tasks: provision.yml
  when:
  - not delete_demo

# - name: Configure AMQ Streams
#   include_tasks: configure.yml
#   when:
#   - not delete_demo

# - name: Delete Monitoring
#   include_tasks: delete.yml
#   when: delete_demo | bool
