- hosts: localhost
  name: Install AMQ Streams Monitoring Demo
  vars:
    rhosak: false
    rhoam: false
    cluster_project: kafka-cluster
    kafka_cluster_name: kafka-cluster
    grafana_user: admin
    grafana_password: admin
    insecure_skip_tls_verify: true
    threescale_project: apim
    delete_demo: false
    prometheusHost: prometheus-operated.openshift-monitoring.svc.cluster.local:9090
    grafanaSAToken: grafanaSAToken
  tasks:

    - name: Define domain
      set_fact:
        domain : "{{ server | regex_replace('https://api.') | regex_replace(':6443')   }}"

    - name: login as super user with token on OpenShift 4
      command: "oc login --token={{ token }}  --server={{ server }} --insecure-skip-tls-verify={{ insecure_skip_tls_verify }}"
      when:
       - token is defined
       - server is defined
      ignore_errors: false
    
    - name: Evaluate {{ cluster_project }} Namespace
      k8s:
        state: present
        kind: Project
        api_version: project.openshift.io/v1
        definition:
          metadata:
            name: "{{ cluster_project }}"

    - name: Include AMQ Streams role
      include_role:
        name: streams
      when:
       - rhosak is false

    # - name: Include Threescale role
    #   include_role:
    #     name: threescale

    - name: Install Applications
      include_role:
        name: apps

    - name: Include Monitoring role
      include_role:
        name: monitoring
    
    
